"""Add user_id to Project model

Revision ID: b19145cd5abf
Revises: 
Create Date: 2024-10-01 11:55:37.732364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19145cd5abf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TASK',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('proj_id', sa.String(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('early_start_date', sa.String(), nullable=True),
    sa.Column('early_end_date', sa.String(), nullable=True),
    sa.Column('target_start_date', sa.String(), nullable=True),
    sa.Column('target_end_date', sa.String(), nullable=True),
    sa.Column('total_float_hr_cnt', sa.Float(), nullable=True),
    sa.Column('remain_drtn_hr_cnt', sa.Float(), nullable=True),
    sa.Column('driving_path_flag', sa.String(), nullable=True),
    sa.Column('xer_file_id', sa.Integer(), nullable=True),
    sa.Column('wbs_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('TASKPRED',
    sa.Column('task_pred_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('pred_task_id', sa.String(), nullable=True),
    sa.Column('proj_id', sa.String(), nullable=True),
    sa.Column('pred_type', sa.String(), nullable=True),
    sa.Column('lag_hr_cnt', sa.Float(), nullable=True),
    sa.Column('xer_file_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('task_pred_id')
    )
    op.create_table('TASKRSRC',
    sa.Column('taskrsrc_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('proj_id', sa.String(), nullable=True),
    sa.Column('rsrc_id', sa.String(), nullable=True),
    sa.Column('act_reg_cost', sa.Float(), nullable=True),
    sa.Column('act_ot_cost', sa.Float(), nullable=True),
    sa.Column('target_cost', sa.Float(), nullable=True),
    sa.Column('remain_cost', sa.Float(), nullable=True),
    sa.Column('xer_file_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('taskrsrc_id')
    )
    op.create_table('USER',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('PROJECT',
    sa.Column('proj_id', sa.String(), nullable=False),
    sa.Column('proj_short_name', sa.String(), nullable=True),
    sa.Column('xer_file_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('proj_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PROJECT')
    op.drop_table('USER')
    op.drop_table('TASKRSRC')
    op.drop_table('TASKPRED')
    op.drop_table('TASK')
    # ### end Alembic commands ###
